---
title: "Project Prototype"
author: "Caden Miller"
date: "2025-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, echo = TRUE, include = TRUE)
library(tidyverse)
library(tmap)
library(sf)
```

## Data Cleaning

```{r}
collisions = read_csv("../Datasets/Motor_Vehicle_Collisions_-_Crashes_20251017.csv")
```

```{r}
names(collisions)
```
```{r}
clean_collisions = collisions %>% 
  select(
    LATITUDE,
    LONGITUDE,
    `CRASH DATE`,
    `CRASH TIME`,
    BOROUGH,
    `NUMBER OF PERSONS INJURED`,
    `NUMBER OF PERSONS KILLED`,
    `CONTRIBUTING FACTOR VEHICLE 1`
  ) %>% 
  filter(
    !is.na(LATITUDE),
    !is.na(LONGITUDE),
    between(LONGITUDE, -74.3, -73.6),
    between(LATITUDE, 40.4, 40.95)
  )
```


## Plot Prototype

```{r}
collisions_sf = st_as_sf(
  clean_collisions,
  coords = c("LONGITUDE", "LATITUDE"),
  crs = 4326
)

#PROTOTYPE USE ONLY
#ONLY DISPLAY COLLISIONS IN MANHATTAN TO LIMIT THE NUMBER OF TOTAL POINTS DISPLAYED AT ONCE
collisions_sf = collisions_sf %>% 
  filter(BOROUGH == "MANHATTAN")
```

```{r}
tmap_mode("view")
tm_shape(collisions_sf) +
  tm_basemap("OpenStreetMap") +
  tm_dots(col = "red",
          size = 0.5,
          scale = 0,
          alpha = 0.5,
          popup.vars = c(
            "Date" = "CRASH DATE",
            "Time" = "CRASH TIME",
            "Borough" = "BOROUGH",
            "Injuries" = "NUMBER OF PERSONS INJURED",
            "Deaths" = "NUMBER OF PERSONS KILLED",
            "Main Factor" = "CONTRIBUTING FACTOR VEHICLE 1"
          ))
```

